services:
  - type: web
    name: feedbackev-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_DATABASE
        sync: false

  - type: web
    name: feedbackev
    env: static
    buildCommand: cd Client && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./Client/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: http://localhost:3001 