services:
  - type: web
    name: feedbackev
    env: node
    buildCommand: |
      cd Client && npm install --legacy-peer-deps && npm run build
      cd ../server && npm install
    startCommand: cd server && npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://feedbackev.onrender.com
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_DATABASE
        sync: false 