services:
  - type: web
    name: feedbackev
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: cd server && npm start

    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_DATABASE
        sync: false
      - key: PORT
        value: 10000

